In [6]:
import pandas as pd

In [ ]:
bank_data=pd.read_csv('bank_data.csv')

In [114]:
bank_data.columns

Index(['user_id', 'gender', 'date_of_birth', 'workclass', 'education_level',
       'education_num', 'marital_status', 'occupation', 'relationship',
       'capital_gain', 'capital_loss', 'hours_per_week', 'address', 'email',
       'inquiry_purpose_code', 'institute_type', 'account_type',
       'asset_class_cd', 'asset_code', 'portfolio_type', 'approved',
       'approved_loan_amount'],
      dtype='str')

Part 1: loan value

In [123]:
bank_data_clean=bank_data.drop(columns=['user_id','date_of_birth','address','email','inquiry_purpose_code','asset_class_cd','asset_code'])
bank_data_clean

,gender,workclass,education_level,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,hours_per_week,institute_type,account_type,portfolio_type,approved,approved_loan_amount
0,Male,Private,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,0.0,0.0,40.0,NBF,189.0,I,1.0,1684000.0
1,Male,Private,Assoc-voc,11,Married-civ-spouse,Exec-managerial,Husband,0.0,0.0,40.0,PVT,5.0,R,1.0,317000.0
2,Male,Private,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,0.0,0.0,40.0,PVT,5.0,R,1.0,1363000.0
3,Male,Private,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,0.0,0.0,40.0,HFC,58.0,M,1.0,1154000.0
4,Male,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,0.0,0.0,50.0,PVT,189.0,I,1.0,700000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:

bank_data_clean=bank_data_clean.dropna()
bank_data_clean

,gender,workclass,education_level,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,hours_per_week,institute_type,account_type,portfolio_type,approved,approved_loan_amount
0,Male,Private,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,0.0,0.0,40.0,NBF,189.0,I,1.0,1684000.0
1,Male,Private,Assoc-voc,11,Married-civ-spouse,Exec-managerial,Husband,0.0,0.0,40.0,PVT,5.0,R,1.0,317000.0
2,Male,Private,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,0.0,0.0,40.0,PVT,5.0,R,1.0,1363000.0
3,Male,Private,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,0.0,0.0,40.0,HFC,58.0,M,1.0,1154000.0
4,Male,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,0.0,0.0,50.0,PVT,189.0,I,1.0,700000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,Male,Private,10th,6,Married-civ-spouse,Craft-repair,Husband,0.0,0.0,40.0,NBF,189.0,I,0.0,1161000.0
1496,Male,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,0.0,0.0,40.0,NBF,191.0,I,0.0,930000.0
1497,Female,Private,Bachelors,13,Married-spouse-absent,Adm-clerical,Unmarried,0.0,0.0,40.0,PVT,5.0,R,0.0,1021000.0
1498,Female,Local-gov,Masters,14,Never-married,Prof-specialty,Unmarried,0.0,0.0,40.0,PVT,5.0,R,0.0,627000.0
1499,Male,Private,Assoc-voc,11,Never-married,Craft-repair,Not-in-family,0.0,0.0,30.0,NBF,189.0,I,0.0,1336000.0

In [125]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x_data=pd.get_dummies(bank_data_clean.drop(columns=['approved_loan_amount','approved']))
y_data=bank_data_clean['approved_loan_amount']
x_train, x_test, y_train,y_test= train_test_split(x_data,y_data)
model=LinearRegression().fit(x_train,y_train)

In [126]:
import numpy as np
y_test_pred=np.array(model.predict(x_test))
y_test=np.array(y_test)

In [118]:
def get_accuracy(actual,predicted):
    closeness=abs(1-abs(actual-predicted)/(abs(actual+predicted)/2))
    return float(np.mean(closeness))

In [127]:
get_accuracy(y_test,y_test_pred)

0.5547152634751796

Part 2 (approved or not?)

In [155]:

bank_data_clean=bank_data.drop(columns=['user_id','date_of_birth','address','email','inquiry_purpose_code','asset_class_cd','asset_code'])
bank_data_clean['Age']=2026-pd.to_datetime(bank_data['date_of_birth']).dt.year
bank_data_clean=bank_data_clean.dropna()
non_numerical_cols=['gender','workclass','education_level', 'marital_status','occupation','relationship','institute_type','portfolio_type']
bank_data_clean=pd.get_dummies(bank_data_clean)#,columns=non_numerical_cols)
bank_data_clean

,capital_gain,capital_loss,hours_per_week,account_type,approved,approved_loan_amount,Age,gender_ Female,gender_ Male,gender_F,...,institute_type_FOR,institute_type_HFC,institute_type_INS,institute_type_NBF,institute_type_PUB,institute_type_PVT,institute_type_SRC,portfolio_type_I,portfolio_type_M,portfolio_type_R
0,0.0,0.0,40.0,189.0,1.0,1684000.0,65.0,False,True,False,...,False,False,False,True,False,False,False,True,False,False
1,0.0,0.0,40.0,5.0,1.0,317000.0,59.0,False,True,False,...,False,False,False,False,False,True,False,False,False,True
2,0.0,0.0,40.0,5.0,1.0,1363000.0,57.0,False,True,False,...,False,False,False,False,False,True,False,False,False,True
3,0.0,0.0,40.0,58.0,1.0,1154000.0,47.0,False,True,False,...,False,True,False,False,False,False,False,False,True,False
4,0.0,0.0,50.0,189.0,1.0,700000.0,68.0,False,True,False,...,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.0,0.0,40.0,189.0,0.0,1161000.0,40.0,False,True,False,...,False,False,False,True,False,False,False,True,False,False
1496,0.0,0.0,40.0,191.0,0.0,930000.0,30.0,False,True,False,...,False,False,False,True,False,False,False,True,False,False
1497,0.0,0.0,40.0,5.0,0.0,1021000.0,49.0,True,False,False,...,False,False,False,False,False,True,False,False,False,True
1498,0.0,0.0,40.0,5.0,0.0,627000.0,48.0,True,False,False,...,False,False,False,False,False,True,False,False,False,True
1499,0.0,0.0,30.0,189.0,0.0,1336000.0,47.0,False,True,False,...,False,False,False,True,False,False,False,True,False,False

In [162]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
x_data=bank_data_clean.drop(columns=['approved_loan_amount','approved'])
y_data=bank_data_clean['approved']  
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data)
model=RandomForestClassifier().fit(x_test,y_test)
print("Accuracy Score:",accuracy_score(model.predict(x_test),y_test)*100,"%")

Accuracy Score: 99.73262032085562 %